---
# tasks file for setup-distro

- name: Run Fedora related tasks if distribution is Fedora
  include_tasks: fedora/main.yml
  when: 
    ansible_distribution == "Fedora"

# Make sure to configure Flathub in the respective distro folder
- name: Install flatpak applications
  community.general.flatpak:
    name: "{{ item }}"
    remote: flathub
    state: present
  with_items: "{{ flatpak }}"
